"""Generate src/psx_card_new_cards.h from the missing-card diff + yugipedia stats."""
import json, io, os
SP = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(SP, "..", ".."))   # repo root
# The name-offset table's free filler used to stop at 767, which capped this
# at 44 cards. psx_card_extend.c now moves the monster-type / Guardian-Star
# string block off string ids 0x8300+ (one word at 0x80037F14 plus 34 mirrored
# table entries), which frees indices 768..807 as well -- see NAME_FREE_LAST.
# The pool holds 69 usable monsters (723..791) and psx_card_chest.c's stretch
# needs an EVEN card count (its u16 tail fields shift by 3*D and that has to
# stay halfword-aligned), so 68 it is: ids 723..790.
FIRST, LAST = 723, 790

RAW_ASCII = (
    " etaoinsrhl.dumcgywfpbk\0Av I'TSM,DOWHYER\0\0GLCNB\0P-Fzkjjxq"  # placeholder, replaced below
)
TABLE = {
 0x00:' ',0x01:'e',0x02:'t',0x03:'a',0x04:'o',0x05:'i',0x06:'n',0x07:'s',
 0x08:'r',0x09:'h',0x0A:'l',0x0B:'.',0x0C:'d',0x0D:'u',0x0E:'m',0x0F:'c',
 0x10:'g',0x11:'y',0x12:'w',0x13:'f',0x14:'p',0x15:'b',0x16:'k',
 0x18:'A',0x19:'v',0x1A:'I',0x1B:"'",0x1C:'T',0x1D:'S',0x1E:'M',0x1F:',',
 0x20:'D',0x21:'O',0x22:'W',0x23:'H',0x24:'Y',0x25:'E',0x26:'R',
 0x29:'G',0x2A:'L',0x2B:'C',0x2C:'N',0x2D:'B',0x2F:'P',
 0x30:'-',0x31:'F',0x32:'z',0x33:'K',0x34:'j',0x35:'U',0x36:'x',0x37:'q',
 0x38:'0',0x39:'V',0x3A:'2',0x3B:'J',0x3C:'#',0x3D:'1',0x3E:'Q',0x3F:'Z',
 0x41:'3',0x42:'5',0x43:'&',0x45:'7',0x46:'X',
 0x4A:'4',0x4E:'6',0x57:'8',0x59:'9',
}
ENC = {}
for k, v in TABLE.items():
    ENC.setdefault(v, k)

TYPES = ['Dragon','Spellcaster','Zombie','Warrior','Beast-Warrior','Beast','Winged Beast',
         'Fiend','Fairy','Insect','Dinosaur','Reptile','Fish','Sea Serpent','Machine',
         'Thunder','Aqua','Pyro','Rock','Plant']
GSNAME = [None,'Mars','Jupiter','Saturn','Uranus','Pluto','Neptune','Mercury','Sun','Moon','Venus']

missing = json.load(io.open(os.path.join(SP,'missing.json'), encoding='utf-8'))
stats   = json.load(io.open(os.path.join(SP,'new_monsters.json'), encoding='utf-8'))
conv    = {int(k): tuple(v) for k, v in
           json.load(io.open(os.path.join(SP,'gs_convention.json'), encoding='utf-8')).items()}

mons = [m for m in missing if m['type'] == 'Monster Card']
rows = []
for m in mons:
    s = stats.get(m['name'])
    if not s or s['atk'] is None or s['type'] not in TYPES:
        print('SKIP (no usable stats):', m['name'], s and s['type']); continue
    atk, dfd = int(s['atk']), int(s['def'])
    if atk % 10 or dfd % 10 or atk > 5110 or dfd > 5110:
        print('SKIP (unrepresentable ATK/DEF):', m['name'], atk, dfd); continue
    name = m['name']
    if any(ch not in ENC for ch in name):
        print('SKIP (unencodable name):', name, [ch for ch in name if ch not in ENC]); continue
    t = TYPES.index(s['type'])
    g1, g2 = conv[t]
    rows.append({'name': name, 'atk': atk, 'def': dfd, 'type': t, 'g1': g1, 'g2': g2,
                 'date': m['date']})

rows = rows[:LAST - FIRST + 1]
print('\nusable monsters: %d  -> ids %d..%d' % (len(rows), FIRST, FIRST + len(rows) - 1))

def enc(name):
    return [ENC[c] for c in name] + [0xFF]

out = []
out.append('/* Generated by scratchpad/gen_new_cards.py -- do not edit by hand.')
out.append(' *')
out.append(' * Real Yu-Gi-Oh cards that Forbidden Memories does not have. The list is the')
out.append(' * maintainer\'s yugipedia debut-date query, diffed against the game\'s own 722')
out.append(' * (every FMR page\'s `main =` gives the card\'s canonical name, so a card FM')
out.append(' * ships under an older name -- Wicked Mirror = Archfiend Mirror, Kaminarikozou')
out.append(' * = Thunder Kid -- is correctly recognised as already present).')
out.append(' *')
out.append(' * MONSTERS ONLY, deliberately: an FM monster is entirely described by the data')
out.append(' * below, so these duel correctly. A Spell or Trap would also need its EFFECT,')
out.append(' * which FM binds to specific card ids in code, and would sit in the deck doing')
out.append(' * nothing.')
out.append(' *')
out.append(' * Guardian Stars are an FM invention with no real-world counterpart, so each')
out.append(' * card gets the most common pair among the stock cards of its type (measured;')
out.append(' * see gs_convention.json). ATK/DEF/type are the card\'s real values.')
out.append(' */')
out.append('#ifndef PSX_CARD_NEW_CARDS_H')
out.append('#define PSX_CARD_NEW_CARDS_H')
out.append('')
out.append('typedef struct {')
out.append('    const char *name;      /* for the log/OSD; the guest gets NAME_BYTES */')
out.append('    uint8_t     enc[48];   /* name in the game\'s code table, 0xFF-terminated */')
out.append('    uint8_t     enc_len;')
out.append('    uint16_t    atk, def;  /* real values; the word stores them /10 */')
out.append('    uint8_t     type;      /* 0..19, the stock type enum */')
out.append('    uint8_t     gs1, gs2;  /* 1..10 */')
out.append('} PsxNewCard;')
out.append('')
out.append('static const PsxNewCard PSX_NEW_CARDS[] = {')
for r in rows:
    e = enc(r['name'])
    out.append('    { "%s",' % r['name'].replace('"','\\"'))
    out.append('      { %s }, %d,' % (', '.join('0x%02X' % b for b in e), len(e)))
    out.append('      %d, %d, %d, %d, %d },   /* %s / %s%s */' % (
        r['atk'], r['def'], r['type'], r['g1'], r['g2'],
        GSNAME[r['g1']], GSNAME[r['g2']], '  ' + TYPES[r['type']]))
out.append('};')
out.append('')
out.append('#endif /* PSX_CARD_NEW_CARDS_H */')
io.open(os.path.join(REPO,'src','psx_card_new_cards.h'),'w',encoding='utf-8',newline='\n').write('\n'.join(out)+'\n')
print('wrote src/psx_card_new_cards.h with %d cards' % len(rows))
print('\nid   name                                   ATK/DEF   type          GS')
for i,r in enumerate(rows):
    print('%3d  %-38s %4d/%-4d %-13s %s/%s' % (FIRST+i, r['name'], r['atk'], r['def'],
          TYPES[r['type']], GSNAME[r['g1']], GSNAME[r['g2']]))
